### ISSUE TITLE
icon picker is behindert editor on small viewports

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#2262]

**Comment by bjalder26** [comment]
I think it is related to this.

```css
@media (max-width: 1000px) and (min-aspect-ratio: 16 / 20) {
#editorModules {
    left: 0;
    top: var(--editToolbarHeight);
    right: var(--editSidebarWidth);
    bottom: 0;
    width: unset!important;
    min-width: unset!important;
    max-width: unset!important;
    height: unset;
}
}
```
