### ISSUE TITLE
html card objects have white background until the room reloads (then it's transparent)

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#2278]
Upon further investigation it is edit mode (white) vs play mode (transparent).

This causes it:

```CSS
body.edit.darkMode {
  color-scheme: dark;
}
```

No issue in Chrome.
