### ISSUE TITLE
The number of stars in starred games is out of position

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#2355]
For example, see this image.  The number 15 should be near the star.

![Screenshot 2024-11-02 110650](https://github.com/user-attachments/assets/645c6594-c96c-4c49-8e38-dc79b826208b)

**Comment by bjalder26** [comment]
I would guess changing top to ~17px is probably what you want.  It is currently at 51px.

![image](https://github.com/user-attachments/assets/13928461-a4a0-4447-8438-673939a8b3bd)

```css
#mainImage span {
    position: absolute;
    font-size: 16px;
    top: 17px;
    width: 62px;
    text-align: center;
    color: #fff;
    font-weight: 700;
}
```
