### ISSUE TITLE
[Docker] Images are failing to load

### ISSUE THREAD

**Issue by clockwinder** [ArnoldSmith86/virtualtabletop#2393]
When running the [Docker image ](https://hub.docker.com/r/arnoldsmith86/virtualtabletop) using this docker compose:
```yaml
version: '3.9'
services:
  virtualtabletop:
    container_name: virtualtabletop
    image: arnoldsmith86/virtualtabletop
    ports:
      - 8272:8272
    volumes:
      - /local/path/save:/app/save
    restart: unless-stopped
```
Most of the images on the page are failing to load.
![image](https://github.com/user-attachments/assets/82461139-b3e7-4265-a69c-60a2c43da178)

With some exceptions:
![image](https://github.com/user-attachments/assets/1ed07039-591a-4fb7-950a-caa33e032a01)

This appears to also be the case when a game is launched:
![image](https://github.com/user-attachments/assets/32858870-e111-49b3-ae10-58dde682a564)

If I inspect one of the missing images, I can see it's linked to `http://localhost:8272/assets/-1594585426_640982` but I'm connecting to my server from a different local address.

```yaml
    environment:
      - EXTERNALURL=
```
So I added the above to my docker compose, and now the page seems to be functioning the way I would expect:
![image](https://github.com/user-attachments/assets/58af4d91-87b8-4b56-ad28-c5d06a886b2d)

Is this the expected behaviour?
