### ISSUE TITLE
[Docker] 

### ISSUE THREAD

**Issue by clockwinder** [ArnoldSmith86/virtualtabletop#2394]
When running the [docker image](https://hub.docker.com/r/arnoldsmith86/virtualtabletop) using this docker compose:
```yaml
version: '3.9'
services:
  virtualtabletop:
    container_name: virtualtabletop
    image: arnoldsmith86/virtualtabletop
#    user: 1001:100
    ports:
      - 8272:8272
    volumes:
      - /local/path/save:/app/save
    environment:
      - EXTERNALURL=
    restart: unless-stopped
```
The application seems to mostly work just fine.

But as soon as I uncomment `user: 1001:100` (the UID/GID I want this application to run as), I get this error in the log:
```
node:fs:2982
  handleErrorFromBinding(ctx);
  ^
Error: EACCES: permission denied, copyfile '/app/config.template.json' -> '/app/config.json'
    at Object.copyFileSync (node:fs:2982:3)
    at new Config (file:///app/server/config.mjs:7:10)
    at file:///app/server/config.mjs:56:16
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: '/app/config.template.json',
  dest: '/app/config.json'
}
```

It would be nice to have the option to run this container as a non-root user, if that's something which could be supported!
